# Generated by Django 4.2.23 on 2025-07-13 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name_plural": "用户"},
        ),
        migrations.AlterModelTable(
            name="user",
            table="用户",
        ),
    ]
