# Generated by Django 4.2.23 on 2025-07-23 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0004_hotprojects"),
    ]

    operations = [
        migrations.CreateModel(
            name="CveSpider",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("cve_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("description_cn", models.TextField()),
                ("url", models.CharField(max_length=255)),
                ("if_sent", models.IntegerField()),
                ("if_chosen", models.IntegerField()),
                ("published_time", models.CharField(max_length=255)),
                ("created_time", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_time", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "cve_spider",
            },
        ),
    ]
