# Generated by Django 4.2.23 on 2025-07-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0005_cvespider"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotprojects",
            old_name="tags",
            new_name="tag",
        ),
    ]
