# Generated by Django 4.2.23 on 2025-07-24 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0006_rename_tags_hotprojects_tag"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hotprojects",
            old_name="create_time",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="hotprojects",
            old_name="update_time",
            new_name="updated_time",
        ),
    ]
