# Generated by Django 4.2.23 on 2025-07-29 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0007_rename_create_time_hotprojects_created_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotprojects",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
