# Generated by Django 4.2.23 on 2025-07-29 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0008_alter_hotprojects_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotprojects',
            name='tag',
            field=models.TextField(blank=True, null=True),
        ),
    ]
