# Generated by Django 4.2.23 on 2025-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_app", "0009_alter_hotprojects_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account",
                    models.CharField(max_length=50, unique=True, verbose_name="账号"),
                ),
                ("password", models.CharField(max_length=128, verbose_name="密码")),
                (
                    "is_admin",
                    models.BooleanField(default=False, verbose_name="是否是管理员"),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
            ],
            options={
                "verbose_name": "用户表",
                "verbose_name_plural": "用户表",
                "db_table": "user_table",
                "ordering": ["-create_time"],
            },
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AlterField(
            model_name="hotprojects",
            name="tag",
            field=models.TextField(),
        ),
    ]
