# Generated by Django 4.2.23 on 2025-07-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Send_Email", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotProjects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("description", models.TextField()),
                ("url", models.URLField()),
                ("tags", models.TextField()),
                ("type", models.IntegerField()),
                ("if_sent", models.IntegerField(verbose_name=0)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SendEmailConfig",
        ),
    ]
