# Generated by Django 4.2.23 on 2025-07-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Send_Email", "0002_hotprojects_delete_sendemailconfig"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="hotprojects",
            table="热点表",
        ),
    ]
